### ISSUE TITLE
Parameters not transferred

### ISSUE THREAD

**Issue by MrDoomsday** [dadongshangu/async_FIFO#4]
![image](https://github.com/dadongshangu/async_FIFO/assets/46083992/40bb7d6e-6f52-4f4f-a239-15790fc62083)

In the top module, the sync_r2w and sync_w2r synchronization submodules are not assigned an address bus width. This causes errors when you change the FIFO depth.

**Comment by dadongshangu** [comment]
I just merged your request. Thanks.

**Comment by dadongshangu** [comment]
Close this topic as alreay merged.
